name: Release
description: Do the release
inputs:
  version:
    description: Version to release
    required: true
  changelog:
    description: The changelog
    required: true
  issues-closed:
    description: Issues we've closed
  crates-io-token:
    description: crates.io API token
    required: true
runs:
  using: composite
  steps:
    - name: Git add
      shell: bash
      run: git add Cargo.toml Cargo.lock
    - name: Commit version bump
      shell: bash
      run: 'git commit -m "chore: Bump package version to ${{ inputs.version }}"'
    - name: Git tag
      shell: bash
      run: git tag "${{ inputs.version }}"
    - name: Get last commit sha
      shell: bash
      id: last-commit
      run: echo "sha=$(git log -n 1 --pretty=format:%H)" >> $GITHUB_OUTPUT
    - name: Push commit
      shell: bash
      run: git push
    - name: Push tag
      shell: bash
      run: git push --tags
    - name: Publish crate
      shell: bash
      run: cargo publish --locked --token ${{ inputs.crates-io-token }}
    - name: Create release
      uses: ncipollo/release-action@v1
      with:
        allowUpdates: false
        prerelease: false
        generateReleaseNotes: false
        commit: ${{ steps.last-commit.outputs.sha }}
        tag: ${{ inputs.version }}
        body: ${{ inputs.changelog }}
    - name: Notify
      if: ${{ inputs.issues-closed }}
      uses: alorel-actions/semantic-release-lite/notify@v0
      with:
        tag: ${{ inputs.version }}
        issues: ${{ inputs.issues-closed }}
        allow-out-of-sync: true
