name: Test
on:
  workflow_call: { }
  push:
    branches:
      - master
  pull_request: {}

permissions:
  contents: read

env:
  CARGO_INCREMENTAL: 0
  RUSTFLAGS: --deny warnings

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Init toolchain
        uses: alorel-actions/cargo/init@v2
        with:
          components: rustfmt,clippy
          cache-prefix: lint
          local: true

      - name: Fmt
        run: cargo fmt --check

      - name: Clippy
        run: cargo clippy --workspace --tests --examples --locked --no-deps

      - name: Doc
        run: cargo doc --workspace --no-deps && rm -rf target/doc

      - name: cargo-rdme
        uses: alorel-actions/cargo/rdme@v2
        with:
          intralinks-strip-links: true

  nightly-test:
    name: Rust nightly
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Init toolchain
        uses: alorel-actions/cargo/init@v2
        with:
          toolchain: nightly-2025-05-05
          cache-prefix: test
          local: true
          components: llvm-tools-preview

      - name: Examples & unit tests
        uses: alorel-actions/cargo/llvm-cov@v2
        with:
          output: unit.lcov
          args: --lcov --examples --tests --workspace

      - name: Doc tests
        uses: alorel-actions/cargo/llvm-cov@v2
        with:
          output: doc.lcov
          args: --lcov --doctests --workspace

      - name: Upload coverage
        uses: coverallsapp/github-action@v2
        continue-on-error: true
        with:
          files: unit.lcov doc.lcov

  test:
    name: Rust ${{matrix.toolchain}}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        toolchain:
          - stable
          - 1.71.1
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Init toolchain
        uses: alorel-actions/cargo/init@v2
        with:
          toolchain: ${{matrix.toolchain}}
          cache-prefix: test
          local: true

      - name: Build
        run: cargo build --locked

      - name: Test
        run: cargo test --locked
